#!/usr/bin/env python3
"""Package the manuscript's exact TeX, figure, table and font dependencies."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PAPER = 'manuscript/TRIX_REVISION.tex'
FONT_MANIFEST = 'manuscript/fonts/manifest.json'
DEPENDENCY = re.compile(r'\\(?:includegraphics(?:\[[^]]*\])?|input)\{([^}]+)\}')
INSTRUCTIONS = """# TRiX main manuscript for Overleaf

1. In Overleaf, choose New Project > Upload Project and upload this ZIP.
2. Set the main document to main.tex and the compiler to XeLaTeX.
3. Recompile. If using an existing project, choose Recompile from scratch.

Upload the complete ZIP. Keep the manuscript/ directory and its contents.
The project includes all five figure assets, both included table fragments
and the exact text/math fonts, with their licence. References are in main.tex;
no separate bibliography file or bibliography program is required.

main.tex is an exact copy of the repository's manuscript/TRIX_REVISION.tex.
The root latexmkrc also selects XeLaTeX. Local build: latexmk main.tex.
OVERLEAF_MANIFEST.json maps payload files to source paths and SHA-256 hashes.

This is the manuscript compilation package. The complete research source,
response letter and raw experimental evidence are supplied separately.
"""


def sha(data):
    return hashlib.sha256(data).hexdigest()


def payload():
    sources = {'main.tex': PAPER}
    pending = [PAPER]
    visited = set()
    while pending:
        path = pending.pop()
        if path in visited:
            continue
        visited.add(path)
        # TeX comments cannot introduce a dependency.
        tex = re.sub(r'(?<!\\)%[^\n]*', '', (ROOT / path).read_text())
        for name in DEPENDENCY.findall(tex):
            dep = (ROOT / name).resolve()
            if not dep.is_relative_to(ROOT) or not dep.is_file():
                raise ValueError(f'Missing or external TeX dependency: {name}')
            sources[name] = name
            if name.endswith('.tex'):
                pending.append(name)
    fonts = json.loads((ROOT / FONT_MANIFEST).read_text())
    sources[FONT_MANIFEST] = FONT_MANIFEST
    license_path = 'manuscript/fonts/' + fonts['license']
    sources[license_path] = license_path
    for name, metadata in fonts['files'].items():
        path = 'manuscript/fonts/' + name
        if sha((ROOT / path).read_bytes()) != metadata['sha256']:
            raise ValueError(f'Font hash mismatch: {path}')
        sources[path] = path
    data = {name: (ROOT / source).read_bytes() for name, source in sources.items()}
    data['latexmkrc'] = b"$pdf_mode = 5;\n@default_files = ('main.tex');\n"
    data['README_OVERLEAF.md'] = INSTRUCTIONS.encode()
    manifest = {'schema': 1, 'main_document': 'main.tex', 'compiler': 'XeLaTeX',
                'files': {name: {'sha256': sha(content),
                    'source': sources.get(name, 'generated by scripts/build_overleaf_bundle.py')}
                    for name, content in sorted(data.items())}}
    data['OVERLEAF_MANIFEST.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    return data


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=ROOT / 'build/TRIX_overleaf.zip')
    args = parser.parse_args()
    files = payload()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            entry = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o100644 << 16
            archive.writestr(entry, content)
    with zipfile.ZipFile(args.out) as archive:
        assert set(archive.namelist()) == set(files)
        assert all(archive.read(name) == content for name, content in files.items())
    print(json.dumps({'output': str(args.out), 'files': len(files),
                      'bytes': args.out.stat().st_size,
                      'sha256': sha(args.out.read_bytes())}, indent=2))


if __name__ == '__main__':
    main()
