#!/usr/bin/env python3
"""Package the manuscript's exact TeX, figure, table and font dependencies."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import zipfile

ROOT = Path(__file__).resolve().parents[1]
PAPER = 'manuscript/TRIX_REVISION.tex'
SUPPLEMENT = 'manuscript/TRIX_SUPPLEMENT.tex'
FONT_MANIFEST = 'manuscript/fonts/manifest.json'
DEPENDENCY = re.compile(r'\\(?:includegraphics(?:\[[^]]*\])?|input)\{([^}]+)\}')
INSTRUCTIONS = """# TRiX manuscript and Supplementary Information for Overleaf

1. Choose New Project > Upload Project and upload this complete ZIP.
2. Select TRIX_MAIN.tex as the main document and XeLaTeX as the compiler.
3. Recompile. In an existing project, choose Recompile from scratch.
4. To build the separate supplement, select TRIX_SUPPLEMENT.tex as the main
   document and recompile. Switch back to TRIX_MAIN.tex for the main paper.

Keep the manuscript/ directory and its contents. The two documents have
separate pagination and bibliographies. S-prefixed sections/tables are in
the supplement. Cross-document numbers are supplied in a generated input;
neither document requires the other document's compiled auxiliary files.

All five figure assets, all included table fragments, cross-references and
exact text/math fonts with their licence are included. No bibliography
program or separate bibliography file is required. The root documents are
exact copies of manuscript/TRIX_REVISION.tex and manuscript/TRIX_SUPPLEMENT.tex
in the repository. OVERLEAF_MANIFEST.json records source paths and SHA-256 hashes.

Local builds: latexmk TRIX_MAIN.tex and latexmk TRIX_SUPPLEMENT.tex.
The root latexmkrc selects XeLaTeX and defaults to the main paper.
Research source, the response letter and raw evidence are supplied separately.
"""


def sha(data):
    return hashlib.sha256(data).hexdigest()


def payload():
    sources = {'TRIX_MAIN.tex': PAPER, 'TRIX_SUPPLEMENT.tex': SUPPLEMENT}
    # The journal requests separate figure files and legends at the end.
    # These assets therefore remain dependencies even without inline graphics.
    for item in json.loads((ROOT / 'docs/repository_manifest.json').read_text())['paper_items']:
        if item['document'] == PAPER and item['label'].startswith('fig:'):
            for path in item['files']:
                if path.startswith('manuscript/figures/') and path.endswith(('.pdf', '.png', '.jpg', '.jpeg')):
                    sources[path] = path
    pending = [PAPER, SUPPLEMENT]
    visited = set()
    while pending:
        path = pending.pop()
        if path in visited:
            continue
        visited.add(path)
        # TeX comments cannot introduce a dependency.
        tex = re.sub(r'(?<!\\)%[^\n]*', '', (ROOT / path).read_text())
        for name in DEPENDENCY.findall(tex):
            dep = (ROOT / name).resolve()
            if not dep.is_relative_to(ROOT) or not dep.is_file():
                raise ValueError(f'Missing or external TeX dependency: {name}')
            sources[name] = name
            if name.endswith('.tex'):
                pending.append(name)
    fonts = json.loads((ROOT / FONT_MANIFEST).read_text())
    sources[FONT_MANIFEST] = FONT_MANIFEST
    license_path = 'manuscript/fonts/' + fonts['license']
    sources[license_path] = license_path
    for name, metadata in fonts['files'].items():
        path = 'manuscript/fonts/' + name
        if sha((ROOT / path).read_bytes()) != metadata['sha256']:
            raise ValueError(f'Font hash mismatch: {path}')
        sources[path] = path
    data = {name: (ROOT / source).read_bytes() for name, source in sources.items()}
    data['latexmkrc'] = b"$pdf_mode = 5;\n@default_files = ('TRIX_MAIN.tex');\n"
    data['README_OVERLEAF.md'] = INSTRUCTIONS.encode()
    manifest = {'schema': 2, 'main_document': 'TRIX_MAIN.tex',
                'supplement_document': 'TRIX_SUPPLEMENT.tex', 'compiler': 'XeLaTeX',
                'files': {name: {'sha256': sha(content),
                    'source': sources.get(name, 'generated by scripts/build_overleaf_bundle.py')}
                    for name, content in sorted(data.items())}}
    data['OVERLEAF_MANIFEST.json'] = (json.dumps(manifest, indent=2) + '\n').encode()
    return data


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--out', type=Path, default=ROOT / 'build/TRIX_overleaf.zip')
    args = parser.parse_args()
    files = payload()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.out, 'w', compression=zipfile.ZIP_DEFLATED) as archive:
        for name, content in sorted(files.items()):
            entry = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            entry.compress_type = zipfile.ZIP_DEFLATED
            entry.external_attr = 0o100644 << 16
            archive.writestr(entry, content)
    with zipfile.ZipFile(args.out) as archive:
        assert set(archive.namelist()) == set(files)
        assert all(archive.read(name) == content for name, content in files.items())
    print(json.dumps({'output': str(args.out), 'files': len(files),
                      'bytes': args.out.stat().st_size,
                      'sha256': sha(args.out.read_bytes())}, indent=2))


if __name__ == '__main__':
    main()
