#!/usr/bin/env python3
"""Rebuild the OOD supplementary tables from verified, retained summaries."""
import argparse
import hashlib
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SUMMARY = "results/ood_reset/summary.json"
SEEDS = "results/ood_reset/seed_records.json"
DRAWS = "results/ood_reset/reset_draws.json"
OUTPUT = "manuscript/data/ood_reset_results.tex"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def signed(x):
    return f"{x:+.1f}" if x else "0.0"


def interval(xs):
    return "[" + ", ".join(signed(x) for x in xs) + "]"


def arm_name(name):
    return {"qp_matched": "Matched QP", "trix": "TRiX",
            "box_clip": "Box", "static_clip": "Static",
            "box_clip_preventive": "Prev. box", "trix_preventive": "Prev. TRiX"}[name]


def analyse_inputs(root):
    data = json.loads((root / SUMMARY).read_text())
    seeds = json.loads((root / SEEDS).read_text())
    resets = json.loads((root / DRAWS).read_text())
    assert data["status"] == "complete" and data["episodes"] == 42000 and data["cells"] == 420
    assert len(seeds["records"]) == 420
    assert len(data["arms"]) == 42 and len(data["comparisons"]) == 21
    assert seeds["protocol_sha256"] == resets["protocol_sha256"] == data["protocol_sha256"]
    index = {}
    for r in seeds["records"]:
        k = (r["stage"], r["task"], r["algorithm"], r["evaluation_arm"],
             r["evaluation_distribution"]["condition"])
        index.setdefault(k, []).append(r)
        counts = r["counts"]
        assert counts["episodes"] == 100
        assert sum(counts[name] for name in ("safe_completions", "unsafe_completions_intact",
                   "destructive_completions", "mechanical_failures", "timeouts")) == 100
    for a in data["arms"]:
        key = tuple(a[k] for k in ("stage", "task", "algorithm", "arm", "condition"))
        records = sorted(index[key], key=lambda r:r["seed"])
        assert [r["seed"] for r in records] == list(range(10))
        for name,m in a["metrics"].items():
            counts = [r["counts"][name] for r in records]
            assert counts == m["counts_by_seed"]
            assert abs(np.mean(counts)-m["mean_percent"]) < 1e-12
            assert m["denominator_per_seed"] == 100
        for stratum in ("within", "outside"):
            rows = a["support_strata_descriptive"][stratum]
            assert [r["seed"] for r in rows] == list(range(10))
        assert sum(r["episodes"] for s in a["support_strata_descriptive"].values() for r in s) == 1000
    return data, seeds, resets


def build(root):
    data, seeds, resets = analyse_inputs(root)
    rows = json.loads((root / "docs/ood_reset_protocol.json").read_text())["rows"]
    lookup = {tuple(a[k] for k in ("stage","task","algorithm","arm","condition")):a for a in data["arms"]}
    get = lambda row,arm,c: lookup[(row["stage"],row["task"],row["algorithm"],arm,c)]
    lines = [r"% Generated by scripts/build_ood_reset_tables.py; do not hand-edit numbers.",
        r"\begingroup\small",
        r"\setlength{\tabcolsep}{3pt}", r"\renewcommand{\arraystretch}{1.2}",
        r"\begin{longtable}{@{}L{1.03in}L{1.05in}rccc@{}}",
        r"\caption{Prospective reset-distribution evaluation. ID gives historical in-range safe completion (\%). Shifted entries show mean \%; change from ID (percentage points); and exact 95\% seed-bootstrap interval. Each entry uses ten training seeds with 100 episodes each. Historical contrasts are not episode-paired. Shell draws are outside training support. S1/S2: Stages 1/2. Prev.: matched 15-N preventive specification.}\label{tab:ood-safe}\\",
        r"\toprule Task/policy & Arm & ID & $1.5\times$ & $2\times$ & Shell $2\times$\\\midrule\endfirsthead",
        r"\multicolumn{6}{l}{\small\itshape Table~\ref{tab:ood-safe} (continued)}\\",
        r"\toprule Task/policy & Arm & ID & $1.5\times$ & $2\times$ & Shell $2\times$\\\midrule\endhead"]
    for n,row in enumerate(rows):
        stage = row["stage"][-1]
        for j,arm in enumerate((row["first_arm"],row["second_arm"])):
            label = row["task"] + r"\\" + f'S{stage} {row["algorithm"].upper()}'
            parts = [r"\shortstack[l]{"+label+"}" if j == 0 else "", arm_name(arm)]
            native = get(row,arm,"wide_1p5")["metrics"]["safe_completions"]["baseline_mean_percent"]
            parts.append(f"{native:.1f}")
            for cond in ("wide_1p5","wide_2","shell_2"):
                m = get(row,arm,cond)["metrics"]["safe_completions"]
                parts.append(r"\shortstack{"+f'{m["mean_percent"]:.1f}'+r"\\{\scriptsize "+
                             r"$\Delta$ "+signed(m["mean_delta_pp"])+r"}\\{\scriptsize "+interval(m["ci95_delta_pp"])+"}}")
            lines.append(" & ".join(parts)+(r"\\*" if j == 0 else r"\\"))
        if n < len(rows)-1: lines.append(r"\midrule")
    lines += [r"\bottomrule\end{longtable}\endgroup", "",
        r"\begingroup\small\setlength{\tabcolsep}{4pt}\renewcommand{\arraystretch}{1.15}",
        r"\begin{longtable}{@{}L{1.38in}lrrrrrrll@{}}",
        r"\caption{All outcomes and support strata for the added evaluation. Counts pool the ten seeds descriptively: every row has 1,000 episodes. S/U/D/M/T denote safe completion, unsafe intact completion, destructive completion, mechanical failure and timeout; these five counts sum to 1,000. V counts episodes with outcome-affecting violations and can overlap those categories. The final columns give safe completions/episodes within and outside training support; n/a means an empty stratum. The same 100 reset draws are reused across training seeds and arms within each task/condition, so pooled episodes are not independent training replicates. Raw seed counts, rates and all paired-arm intervals accompany the source data.}\label{tab:ood-outcomes}\\",
        r"\toprule Task/policy/arm & Range & S & U & D & M & T & V & Within & Outside\\\midrule\endfirsthead",
        r"\multicolumn{10}{l}{\small\itshape Table~\ref{tab:ood-outcomes} (continued)}\\",
        r"\toprule Task/policy/arm & Range & S & U & D & M & T & V & Within & Outside\\\midrule\endhead"]
    metrics=("safe_completions","unsafe_completions_intact","destructive_completions",
             "mechanical_failures","timeouts","episodes_with_violation")
    for row in rows:
        for arm in (row["first_arm"],row["second_arm"]):
            for j,cond in enumerate(("wide_1p5","wide_2","shell_2")):
                a=get(row,arm,cond)
                label=f'{row["task"]} S{row["stage"][-1]} {row["algorithm"].upper()}'+r"\\"+arm_name(arm)
                parts=[r"\shortstack[l]{"+label+"}" if j==0 else "",
                       {"wide_1p5":r"$1.5\times$","wide_2":r"$2\times$","shell_2":"Shell"}[cond]]
                parts += [str(sum(a["metrics"][m]["counts_by_seed"])) for m in metrics]
                for stratum in ("within","outside"):
                    entries=a["support_strata_descriptive"][stratum]
                    count=sum(e["counts"]["safe_completions"] for e in entries)
                    denom=sum(e["episodes"] for e in entries)
                    parts.append(f"{count}/{denom}" if denom else "n/a")
                lines.append(" & ".join(parts)+(r"\\*" if j < 2 else r"\\"))
            lines.append(r"\addlinespace[3pt]")
    lines += [r"\bottomrule\end{longtable}\endgroup", ""]
    return "\n".join(lines), data


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=ROOT)
    ap.add_argument("--check", action="store_true")
    args=ap.parse_args()
    tex, data=build(args.root)
    out=args.root/OUTPUT
    if args.check:
        assert out.read_text()==tex
    else:
        out.write_text(tex)
    print(json.dumps({"verified_cells":data["cells"],"episodes":data["episodes"],
                      "tables":2,"output":str(out),"sha256":sha(out)},indent=2))


if __name__ == "__main__":
    main()
